#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""KB index generator v0.1 (HR) — M2 structure ops
Input: KB document list JSON (agent exports via knowledge_list_documents + stats)
Output: research-paper-library-index.md (auto-updated on every ingestion)
Usage: python3 kb-index-gen.py --docs docs.json [--stats stats.json] [--out PATH]
"""
__version__ = '1.0.0'  # ★ R006 ⑥ 唯一版本声明处（补课生成）

import argparse, json, os, datetime


# ★ R006 ⑦ 统一日志：固定路径，失败也留痕（r006-batch-apply 自足插入）
LOG = os.path.expanduser("~/dsh-collab/logs/kb-index-gen.log")


def log(msg):
    """★ R006 ⑦：固定路径日志；失败也留痕。"""
    import time as _t
    try:
        os.makedirs(os.path.dirname(LOG), exist_ok=True)
        with open(LOG, "a", encoding="utf-8") as f:
            f.write("%s %s\n" % (_t.strftime("%Y-%m-%dT%H:%M:%S"), msg))
    except Exception:
        pass

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--docs", required=True)
    ap.add_argument("--stats", default=None)
    ap.add_argument("--out", default=os.path.expanduser("~/dsh-collab/research/ops-science/research-paper-library-index.md"))
    args = ap.parse_args()
    docs = json.load(open(args.docs, encoding="utf-8")).get("documents", [])
    stats = {}
    if args.stats and os.path.exists(args.stats):
        stats = json.load(open(args.stats, encoding="utf-8"))
    L = ["# 研究论文库索引 · ops-science-research (AUTO-GENERATED)", "",
         "> 自动生成: " + datetime.date.today().isoformat() + " · 工具: kb-index-gen.py v0.1 · 随入库更新",
         "> 库: afa7de13-011a-4c73-a9d6-13492c05cdf7",
         "- documents: " + str(len(docs)),
         "- " + ("chunks: " + str(stats.get("chunkCount", "?")) + " · chars: " + str(stats.get("charCount", "?")) + " · tokens: " + str(stats.get("tokenCount", "?")) + " · embedded: " + str(stats.get("embedded", "?")) if stats else "stats 未提供"),
         "", "## 文档清单", "", "| # | 文档 | chunks |", "|---|---|---|"]
    for i, d in enumerate(sorted(docs, key=lambda x: -x.get("chunkCount", 0)), 1):
        L.append("| " + str(i) + " | " + d.get("title", "?") + " | " + str(d.get("chunkCount", "?")) + " |")
    L.append("")
    L.append("> 检索: knowledge_search(baseId=afa7de13-...) · 更新: 每次入库后运行 kb-index-gen.py")
    L.append("---")
    L.append("*auto-generated by kb-index-gen.py · HR · J40/M2 结构运营*")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f: f.write("\n".join(L))
    print("index written:", args.out, "(" + str(len(docs)) + " docs)")

if __name__ == "__main__":
    main()